<?php require './app/templates/header.phtml'; ?>

<ul class="list-group mt-3">
    <li class="list-group-item list-group-item-dark"><span class="h4">Película: <?= htmlspecialchars($alquiler->titulo) ?></span></li>
    <li class="list-group-item list-group-item-dark"><span class="h4">Usuario: <?= htmlspecialchars($alquiler->usuario) ?></span></li>
    <li class="list-group-item list-group-item-dark"><span class="h4">Fecha: <?= $alquiler->fecha_alquiler ?></span></li>
</ul>

<a href="?action=alquileres" class="btn btn-warning mt-3">Ver todos los alquileres</a>
<a href="?action=home" class="btn btn-success mt-3">Volver al inicio</a>

<?php require './app/templates/footer.phtml'; ?>
