<?php require_once './app/templates/header.phtml' ?>
<h1>Administrar Alquileres</h1>

<a href="?action=formAgregarAlquiler" class="btn btn-success mb-4">+ Nuevo Alquiler</a>

<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Película</th>
            <th>Usuario</th>
            <th>Fecha</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($list as $item): ?>
        <tr>
            <td><?= $item->id_alquiler ?></td>
            <td><?= htmlspecialchars($item->titulo) ?></td>
            <td><?= htmlspecialchars($item->usuario) ?></td>
            <td><?= $item->fecha_alquiler ?></td>
            <td><a href="?action=eliminarAlquiler/<?= $item->id_alquiler ?>" class="btn btn-danger" onclick="return confirm('¿Eliminar alquiler?')">Borrar</a></td>
            <td><a href="?action=editarAlquiler/<?= $item->id_alquiler ?>" class="btn btn-warning">Editar</a></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<?php require_once './app/templates/footer.phtml' ?>
