<?php require_once './app/templates/header.phtml' ?>
<h1>Administrar Películas</h1>

<form method="post" action="?action=agregarPelicula" class="mb-4" enctype="multipart/form-data">
    <label class="h5">Título</label>
    <input type="text" name="titulo" class="form-control mb-2" required>

    <label class="h5">Director</label>
    <input type="text" name="director" class="form-control mb-2" required>

    <label class="h5">¿Está alquilada?</label>
    <input type="hidden" name="alquilada" value="0">
    <input type="checkbox" name="alquilada" value="1"> Sí<br><br>

    <label class="h5">Imagen</label>
    <input type="file" name="imagen" class="form-control mb-2">

    <button type="submit" class="btn btn-success">Agregar Película</button>
</form>

<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Director</th>
            <th>Estado</th>
            <th>Imagen</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($list as $item): ?>
        <tr>
            <td><?= $item->id_pelicula ?></td>
            <td><?= htmlspecialchars($item->titulo) ?></td>
            <td><?= htmlspecialchars($item->director) ?></td>
            <td><?= $item->alquilada ? '🔴 Alquilada' : '🟢 Disponible' ?></td>
            <td>
                <?php if (!empty($item->imagen)): ?>
                    <img src="<?= BASE_URL . $item->imagen ?>" alt="Imagen" width="80" height="120">
                <?php else: ?>
                    Sin imagen
                <?php endif; ?>
            </td>
            <td><a href="?action=eliminarPelicula/<?= $item->id_pelicula ?>" class="btn btn-danger" onclick="return confirm('¿Eliminar película?')">Borrar</a></td>
            <td><a href="?action=editarPelicula/<?= $item->id_pelicula ?>" class="btn btn-warning">Editar</a></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<?php require_once './app/templates/footer.phtml' ?>
