<?php require './app/templates/header.phtml' ?>

<h1>Editar Película</h1>
<form method="post" action="?action=actualizarPelicula/<?= $idPelicula ?>" enctype="multipart/form-data">

    <label>Título</label>
    <input type="text" value="<?= htmlspecialchars($pelicula->titulo) ?>" name="titulo" class="form-control mb-2" required>

    <label>Director</label>
    <input type="text" value="<?= htmlspecialchars($pelicula->director) ?>" name="director" class="form-control mb-2" required>

    <label>¿Está alquilada?</label>
    <input type="hidden" name="alquilada" value="0">
    <input type="checkbox" name="alquilada" value="1" <?php if($pelicula->alquilada == 1) echo "checked"; ?>> Sí<br><br>

    <label>Imagen actual</label><br>
    <?php if (!empty($pelicula->imagen)): ?>
        <img src="<?= BASE_URL . $pelicula->imagen ?>" alt="Imagen" width="100" height="150"><br>
    <?php else: ?>
        Sin imagen disponible
    <?php endif; ?><br>

    <label>Cambiar imagen (opcional)</label>
    <input type="file" name="imagen" class="form-control mb-2">

    <button type="submit" class="btn btn-success">Actualizar</button>
    <a href="?action=peliculas" class="btn btn-secondary">Cancelar</a>
</form>

<?php require './app/templates/footer.phtml' ?>
